# Author: Brandon Chew
# Code start date: 20250717

# Elevation by county dataset generated by Benjamin Wong Blonder
#   https://ourenvironment.berkeley.edu/users/1681101

# Initialization ---------------------

rm(list = ls()) 
cat("\014")  

# Mac setwd
setwd("~/Gladstone Dropbox/Brandon Chew/Lab Member Files/Brandon Chew/R/261")

# # PC setwd
# setwd("C:/Users/brandon.chew/Dropbox (Gladstone)/Lab Member Files/Brandon Chew/R/247")

library(dplyr)
library(ggplot2)
library(readxl)
library(usmap)
library(readr)
library(stringr)
library(usmapdata)

# Data import -----------------------

county.elev <- read.csv("counties_x_elevation.csv")
# county.elev.old <- read_xlsx("county_elev_stats_OLD.xlsx")
cancer.data <- read.delim("BYAREA_COUNTY.TXT", sep = "|")

# med.inc.2020 <- read.csv("ACSST5Y2020.S1901-Data.csv")
med.inc.2021 <- read.csv("ACSST5Y2021.S1901-Data.csv")
# med.inc.2022 <- read.csv("ACSST5Y2022.S1901-Data.csv")
county.diab <- read.csv("DiabetesPercentage.csv")
county.obesity <- read.csv("ObesityAll.csv")

# Data parsing -----------------------

cancer.data <- cancer.data[grepl("^[0-9]",cancer.data$AGE_ADJUSTED_RATE),]

# sanity check
unique(cancer.data$STATE)

for (i in 1:nrow(cancer.data)){
  regex <- regexpr("[0-9]{5}",cancer.data$AREA[i], perl = T)
  cancer.data$FIPS[i] <- substr(cancer.data$AREA[i], regex, regex+4)
}

# med.inc.2020$FIPS <- substr(med.inc.2020$GEO_ID, 
#                             nchar(med.inc.2020$GEO_ID)-4, 
#                             nchar(med.inc.2020$GEO_ID))

med.inc.2021$FIPS <- substr(med.inc.2021$GEO_ID, 
                            nchar(med.inc.2021$GEO_ID)-4, 
                            nchar(med.inc.2021$GEO_ID))

# med.inc.2022$FIPS <- substr(med.inc.2022$GEO_ID, 
#                             nchar(med.inc.2022$GEO_ID)-4, 
#                             nchar(med.inc.2022$GEO_ID))

county.FIPS.codes <- med.inc.2021$GEO_ID
county.FIPS.county <- med.inc.2021$NAME

county.FIPS <- med.inc.2021[,1:2]
county.FIPS[,1] <- county.FIPS.county
county.FIPS[,2] <- county.FIPS.codes

if (grepl("Name",county.FIPS[1,1])){
  county.FIPS <- county.FIPS[-c(1),]
}

rm(county.FIPS.codes)
rm(county.FIPS.county)

colnames(county.FIPS) <- c("Counties","FIPS Codes")

county.FIPS$`FIPS Codes` <- substr(county.FIPS$`FIPS Codes`, 
                                   nchar(county.FIPS$`FIPS Codes`)-4, 
                                   nchar(county.FIPS$`FIPS Codes`))

county.diab$FIPS <- str_pad(county.diab$County_FIPS, 5, pad = "0")
county.obesity$FIPS <- str_pad(county.obesity$County_FIPS, 5, pad = "0")

save.image("CleanStart.RData")

# Elevation dataset from BWB --------------------------------------- 

load("CleanStart.RData")

cancer.data <- cancer.data[cancer.data$RACE=="All Races",]
cancer.data <- cancer.data[cancer.data$SEX=="Male and Female",]

# county.elev$STATEFP <- str_pad(county.elev$STATEFP, 2, pad = "0")
# county.elev$COUNTYFP <- str_pad(county.elev$COUNTYFP, 3, pad = "0")
# 
# county.elev$FIPS <- paste(county.elev$STATEFP,county.elev$COUNTYFP,sep = "")
county.elev$FIPS <- str_pad(county.elev$GEOID, 5, pad = "0")

colnames(county.elev)[10] <- "Elevation"

# alignment of additional correlation datasets
for (i in 1:nrow(cancer.data)){
  if (sum(county.elev$FIPS==cancer.data$FIPS[i])==1){
    cancer.data$elevation[i] <- county.elev$Elevation[county.elev$FIPS==cancer.data$FIPS[i]]
  } else {
    cancer.data$elevation[i] <- NA
  }
}

# for (i in 1:nrow(cancer.data)){
#   if(sum(med.inc.2020$FIPS==cancer.data$FIPS[i])==1){
#     cancer.data$med.inc.2020[i] <- 
#       med.inc.2020$S1901_C01_012E[med.inc.2020$FIPS==cancer.data$FIPS[i]]
#   } else {
#     cancer.data$med.inc.2020[i] <- NA
#   }
# }

for (i in 1:nrow(cancer.data)){
  if(sum(med.inc.2021$FIPS==cancer.data$FIPS[i])==1){
    cancer.data$med.inc.2021[i] <- 
      med.inc.2021$S1901_C01_012E[med.inc.2021$FIPS==cancer.data$FIPS[i]]
  } else {
    cancer.data$med.inc.2021[i] <- NA
  }
}

# for (i in 1:nrow(cancer.data)){
#   if(sum(med.inc.2022$FIPS==cancer.data$FIPS[i])==1){
#     cancer.data$med.inc.2022[i] <- 
#       med.inc.2022$S1901_C01_012E[med.inc.2022$FIPS==cancer.data$FIPS[i]]
#   } else {
#     cancer.data$med.inc.2022[i] <- NA
#   }
# }

for (i in 1:nrow(cancer.data)){
  if(sum(county.diab$FIPS==cancer.data$FIPS[i])==1){
    cancer.data$diab[i] <- 
      county.diab$Diagnosed.Diabetes.Percentage[county.diab$FIPS==cancer.data$FIPS[i]]
  } else {
    cancer.data$diab[i] <- NA
  }
}

for (i in 1:nrow(cancer.data)){
  if(sum(county.obesity$FIPS==cancer.data$FIPS[i])==1){
    cancer.data$obesity[i] <- 
      county.obesity$Obesity.Percentage[county.obesity$FIPS==cancer.data$FIPS[i]]
  } else {
    cancer.data$obesity[i] <- NA
  }
}

rm(list=setdiff(ls(), "cancer.data"))

# cancer.data$med.inc.2020 <- as.numeric(cancer.data$med.inc.2020)
cancer.data$med.inc.2021 <- as.numeric(cancer.data$med.inc.2021)
# cancer.data$med.inc.2022 <- as.numeric(cancer.data$med.inc.2022)

to.plot <- cancer.data[cancer.data$EVENT_TYPE=="Mortality"&
                         cancer.data$SITE=="All Cancer Sites Combined",]
to.plot$AGE_ADJUSTED_RATE <- as.numeric(to.plot$AGE_ADJUSTED_RATE)

# lm.aar.elev <- lm(to.plot$AGE_ADJUSTED_RATE ~ to.plot$elevation)
# 
# glm.aar.elev <- glm(formula = AGE_ADJUSTED_RATE ~ elevation, 
#                     family = poisson(link = "log"), 
#                     data = to.plot)

# ggplot(data = to.plot, aes(x = elevation, y = AGE_ADJUSTED_RATE))+
#   geom_point(size = 2, alpha = 0.5, stroke = 0)+
#   geom_abline(aes(intercept = lm.aar.elev$coefficients[1], 
#                   slope = lm.aar.elev$coefficients[2]))+
#   labs(x = "Elevation (m)", y = "Age adjusted cancer mortality rate")+
#   theme_classic()+
#   theme(legend.position = "none")
# 
# ggplot(data = to.plot, aes(x = elevation, y = log(AGE_ADJUSTED_RATE)))+
#   geom_point()+
#   geom_abline(aes(intercept = glm.aar.elev$coefficients[1], 
#                   slope = glm.aar.elev$coefficients[2]))+
#   labs(x = "Elevation (m)", y = "ln(Age adjusted cancer mortality rate)")+
#   theme_minimal()

# lm.aar.elev.med <- lm(to.plot$AGE_ADJUSTED_RATE ~ to.plot$elevation + 
#                         to.plot$med.inc + 
#                         to.plot$diab +
#                         to.plot$obesity)
# # +                        to.plot$inact)
# a <- summary(lm.aar.elev.med)

glm.aar.elev.med <- glm(formula = AGE_ADJUSTED_RATE ~ elevation + 
                      med.inc.2021 +
                      diab +
                      obesity, 
                    family = poisson(link = "log"), 
                    data = to.plot)
a <- summary(glm.aar.elev.med)

plot.coef <- as.data.frame(a$coefficients)
plot.coef[,5:6] <- confint(glm.aar.elev.med)
plot.coef$coef <- c("intercept","Elevation",
                    "Median Income",
                    "% Diabetic",
                    "% Obese") #,
                    # "% Inactivity")
plot.coef$min <- plot.coef$V5/plot.coef$`Std. Error`
plot.coef$max <- plot.coef$V6/plot.coef$`Std. Error`

ggplot(data = plot.coef[-1,])+
  geom_pointrange(aes(x = coef, y = `z value`, ymin = min, ymax = max), size = 0.01)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  theme_classic()+
  coord_flip()+
  labs(y = "Standardized Estimated Correlation with Age-adjusted Cancer Mortality", 
       x = "")

# USMAP plotting -----------------------------------------------

plot_usmap(regions = "counties")

usmap.elev <- county.elev[,1:3]
usmap.elev[,1] <- county.elev$FIPS
usmap.elev[,2] <- county.elev$Elevation
colnames(usmap.elev) <- c("fips","Elevation","Elev.bracket")

map_with_data_BC <- function (data, values = "values", include = c(), 
                              exclude = c(), na = NA) {
  if (!is.data.frame(data)) {
    stop("`data` must be a data frame")
  }
  if (nrow(data) == 0) {
    if (length(include) == 0) {
      region_type <- "state"
    }
    else {
      region_type <- ifelse(nchar(include[1]) == 2, "state", 
                            "county")
    }
    warning(paste("`data` is empty, returning basic", region_type, 
                  "US map data frame"))
    return(usmap::us_map(regions = region_type, include = include, 
                         exclude = exclude))
  }
  if (!(values %in% names(data))) {
    stop(paste0("\"", values, "\" column not found in `data`."))
  }
  if ("fips" %in% names(data)) {
  }
  else if ("state" %in% names(data)) {
    data$fips <- usmap::fips(data$state)
  }
  else {
    stop("`data` must be a data.frame containing either a `state` or `fips` column.")
  }
  data$fips <- as.character(data$fips)
  region_type <- ifelse(nchar(data$fips[1]) <= 2, "state", 
                        "county")
  map_df <- usmapdata::us_map(regions = region_type, include = include, 
                              exclude = exclude, data_year = 2021)
  data$abbr <- NULL
  data$full <- NULL
  data$county <- NULL
  data$geom <- NULL
  padding <- ifelse(region_type == "state", 2, 5)
  data$fips <- sprintf(paste0("%0", padding, "d"), as.numeric(data$fips))
  result <- merge(map_df, data, by = "fips", all.x = TRUE, 
                  sort = FALSE)
  result[is.na(result[, values]), values] <- na
  result <- result[, c(setdiff(names(result), names(data)), 
                       names(data))]
  if (region_type == "state") {
    result <- result[order(result$full), ]
  }
  else {
    result <- result[order(result$full, result$county), ]
  }
  result
}

plot_usmap_BC <- function(regions = c("states", "state", "counties", "county"), 
                          include = c(), exclude = c(), data = data.frame(), values = "values", 
                          theme = usmap:::theme_map(), labels = FALSE, label_color = "black", 
                          ...) {
  .data <- ggplot2::.data
  regions <- match.arg(regions)
  geom_args <- list(...)
  if (is.null(geom_args[["colour"]]) && is.null(geom_args[["color"]])) {
    geom_args[["color"]] <- "black"
  }
  if (is.null(geom_args[["linewidth"]])) {
    geom_args[["linewidth"]] <- 0.4
  }
  if (is.null(geom_args[["fill"]]) && nrow(data) == 0) {
    geom_args[["fill"]] <- "white"
  }
  if (nrow(data) == 0) {
    map_df <- usmapdata::us_map(regions = regions, include = include, 
                            exclude = exclude)
    geom_args[["mapping"]] <- ggplot2::aes()
  }
  else {
    map_df <- map_with_data_BC(data, values = values, 
                                   include = include, exclude = exclude)
    if (!is.null(map_df$county)) 
      regions <- "counties"
    geom_args[["mapping"]] <- ggplot2::aes(fill = .data[[values]])
  }
  polygon_layer <- do.call(ggplot2::geom_sf, geom_args)
  if (labels) {
    if (regions == "state") 
      regions <- "states"
    else if (regions == "county") 
      regions <- "counties"
    centroid_labels <- usmapdata::centroid_labels(regions)
    if (length(include) > 0) {
      centroid_labels <- centroid_labels[centroid_labels$full %in% 
                                           include | centroid_labels$abbr %in% include | 
                                           centroid_labels$fips %in% include, ]
    }
    if (length(exclude) > 0) {
      centroid_labels <- centroid_labels[!(centroid_labels$full %in% 
                                             exclude | centroid_labels$abbr %in% exclude | 
                                             centroid_labels$fips %in% exclude | substr(centroid_labels$fips, 
                                                                                        1, 2) %in% exclude), ]
    }
    if (regions == "county" || regions == "counties") {
      label_layer <- ggplot2::geom_sf_text(data = centroid_labels, 
                                           ggplot2::aes(label = sub(" County", "", .data$county)), 
                                           color = label_color)
    }
    else {
      label_layer <- ggplot2::geom_sf_text(data = centroid_labels, 
                                           ggplot2::aes(label = .data$abbr), color = label_color)
    }
  }
  else {
    label_layer <- ggplot2::geom_blank()
  }
  ggplot2::ggplot(data = map_df) + polygon_layer + label_layer + 
    theme
}

plot_usmap_BC(regions = "counties", data = usmap.elev, 
              values = "Elevation", linewidth = 0.3)+
  scale_fill_gradient(low = "#800000", high = "#FFFFE3")+
  theme(legend.position = "right")

ggplot(data = usmap.elev)+
  geom_violin(aes(y = Elevation, x = ""))

usmap.ci <- to.plot[,1:3]
usmap.ci[,1] <- to.plot$FIPS
usmap.ci[,2] <- to.plot$AGE_ADJUSTED_RATE

colnames(usmap.ci) <- c("fips","AAMR","AAMR.bracket")

aamr.bracket <- matrix("NA",nrow = nrow(usmap.ci),1)
aamr.bracket[usmap.ci$AAMR<100] <- "50-100"
aamr.bracket[usmap.ci$AAMR<125&usmap.ci$AAMR>=100] <- "100-125"
aamr.bracket[usmap.ci$AAMR<150&usmap.ci$AAMR>=125] <- "125-150"
aamr.bracket[usmap.ci$AAMR<175&usmap.ci$AAMR>=150] <- "150-175"
aamr.bracket[usmap.ci$AAMR<200&usmap.ci$AAMR>=175] <- "175-200"
aamr.bracket[usmap.ci$AAMR>=200] <- "200+"

usmap.ci$AAMR.bracket <- factor(aamr.bracket, 
                                levels = c("50-100","100-125",
                                           "125-150","150-175",
                                           "175-200","200+"),
                                ordered = T)

plot_usmap_BC(regions = "counties", data = usmap.ci, 
           values = "AAMR", color = "black")+
  scale_fill_gradient(low = "#FFFFE3", high = "#800000")

plot_usmap_BC(regions = "counties", data = usmap.ci, 
           values = "AAMR.bracket", color = "black", linewidth = 0.3)+
  scale_fill_manual(values = c("#FFFFE3","#FFCBAB","#FF9377","#BD422E",
                               "#9E2718","#800000",
                               "grey"))+
  theme(legend.position = "right")

ggplot(data = usmap.ci)+
  geom_violin(aes(y = log10(AAMR), x = ""))


# Testing other correlations --------------------------------------

load("CleanStart.RData")

cancer.data <- cancer.data[cancer.data$RACE=="All Races",]
cancer.data <- cancer.data[cancer.data$SEX=="Male and Female",]

for (i in 1:nrow(cancer.data)){
  if (sum(county.elev$FIPS_1==cancer.data$FIPS[i])==1){
    cancer.data$elevation[i] <- county.elev$MEAN[county.elev$FIPS_1==cancer.data$FIPS[i]]
    cancer.data$elevation.sd[i] <- 
      county.elev$STD[county.elev$FIPS_1==cancer.data$FIPS[i]]
  } else {
    cancer.data$elevation[i] <- NA
    cancer.data$elevation.sd[i] <- NA
  }
}

for (i in 1:nrow(cancer.data)){
  if(sum(med.inc$FIPS==cancer.data$FIPS[i])==1){
    cancer.data$med.inc[i] <- 
      med.inc$`Median Household Income (2021)`[med.inc$FIPS==cancer.data$FIPS[i]]
  } else {
    cancer.data$med.inc[i] <- NA
  }
}

for (i in 1:nrow(cancer.data)){
  if(sum(county.diab$FIPS==cancer.data$FIPS[i])==1){
    cancer.data$diab[i] <- 
      county.diab$Diagnosed.Diabetes.Percentage[county.diab$FIPS==cancer.data$FIPS[i]]
  } else {
    cancer.data$diab[i] <- NA
  }
}

for (i in 1:nrow(cancer.data)){
  if(sum(county.inact$FIPS==cancer.data$FIPS[i])==1){
    cancer.data$inact[i] <- 
      county.inact$Physical.Inactivity.Percentage[county.inact$FIPS==cancer.data$FIPS[i]]
  } else {
    cancer.data$inact[i] <- NA
  }
}

for (i in 1:nrow(cancer.data)){
  if(sum(county.obesity$FIPS==cancer.data$FIPS[i])==1){
    cancer.data$obesity[i] <- 
      county.obesity$Obesity.Percentage[county.obesity$FIPS==cancer.data$FIPS[i]]
  } else {
    cancer.data$obesity[i] <- NA
  }
}

# Visually, incidence is also correlated with mortality
#   To address this, will adjust all mortality rates by the incidence rates

to.plot <- cancer.data[cancer.data$SITE=="All Cancer Sites Combined",]

for (i in unique(to.plot$AREA)){
  if(length(to.plot$EVENT_TYPE[to.plot$AREA==i])!=2){
    to.plot <- to.plot[!to.plot$AREA==i,]
  }
}

# Testing other variable subsets ------------------------------------

load("CleanStart.RData")

cancer.data <- cancer.data[cancer.data$RACE=="All Races",]
cancer.data <- cancer.data[cancer.data$EVENT_TYPE=="Mortality"&
                             cancer.data$SITE=="All Cancer Sites Combined",]

cancer.data.male <- cancer.data[cancer.data$SEX=="Male",]
cancer.data.female <- cancer.data[cancer.data$SEX=="Female",]



# males
for (i in 1:nrow(cancer.data.male)){
  if (sum(county.elev$FIPS_1==cancer.data.male$FIPS[i])==1){
    cancer.data.male$elevation[i] <- county.elev$MEAN[county.elev$FIPS_1==cancer.data.male$FIPS[i]]
    cancer.data.male$elevation.sd[i] <- 
      county.elev$STD[county.elev$FIPS_1==cancer.data.male$FIPS[i]]
  } else {
    cancer.data.male$elevation[i] <- NA
    cancer.data.male$elevation.sd[i] <- NA
  }

  if(sum(med.inc$FIPS==cancer.data.male$FIPS[i])==1){
    cancer.data.male$med.inc[i] <- 
      med.inc$`Median Household Income (2021)`[med.inc$FIPS==cancer.data.male$FIPS[i]]
  } else {
    cancer.data.male$med.inc[i] <- NA
  }

  if(sum(county.diab$FIPS==cancer.data.male$FIPS[i])==1){
    cancer.data.male$diab[i] <- 
      county.diab$Diagnosed.Diabetes.Percentage[county.diab$FIPS==cancer.data.male$FIPS[i]]
  } else {
    cancer.data.male$diab[i] <- NA
  }

  if(sum(county.inact$FIPS==cancer.data.male$FIPS[i])==1){
    cancer.data.male$inact[i] <- 
      county.inact$Physical.Inactivity.Percentage[county.inact$FIPS==cancer.data.male$FIPS[i]]
  } else {
    cancer.data.male$inact[i] <- NA
  }

  if(sum(county.obesity$FIPS==cancer.data.male$FIPS[i])==1){
    cancer.data.male$obesity[i] <- 
      county.obesity$Obesity.Percentage[county.obesity$FIPS==cancer.data.male$FIPS[i]]
  } else {
    cancer.data.male$obesity[i] <- NA
  }
}

cancer.data.male$AGE_ADJUSTED_RATE <- as.numeric(cancer.data.male$AGE_ADJUSTED_RATE)

glm.aar.elev <- glm(formula = AGE_ADJUSTED_RATE ~ elevation, 
                    family = poisson(link = "log"), 
                    data = cancer.data.male)
summary(glm.aar.elev)

ggplot(data = glm.aar.elev, aes(x = elevation, y = log(AGE_ADJUSTED_RATE)))+
  geom_point()+
  geom_abline(aes(intercept = glm.aar.elev$coefficients[1], 
                  slope = glm.aar.elev$coefficients[2]))+
  labs(x = "Elevation (m)", y = "ln(Age adjusted cancer mortality rate)",
       title = "Elevation by ln(AAMR) for Males")+
  theme_minimal()

# females
for (i in 1:nrow(cancer.data.female)){
  if (sum(county.elev$FIPS_1==cancer.data.female$FIPS[i])==1){
    cancer.data.female$elevation[i] <- county.elev$MEAN[county.elev$FIPS_1==cancer.data.female$FIPS[i]]
    cancer.data.female$elevation.sd[i] <- 
      county.elev$STD[county.elev$FIPS_1==cancer.data.female$FIPS[i]]
  } else {
    cancer.data.female$elevation[i] <- NA
    cancer.data.female$elevation.sd[i] <- NA
  }
  
  if(sum(med.inc$FIPS==cancer.data.female$FIPS[i])==1){
    cancer.data.female$med.inc[i] <- 
      med.inc$`Median Household Income (2021)`[med.inc$FIPS==cancer.data.female$FIPS[i]]
  } else {
    cancer.data.female$med.inc[i] <- NA
  }
  
  if(sum(county.diab$FIPS==cancer.data.female$FIPS[i])==1){
    cancer.data.female$diab[i] <- 
      county.diab$Diagnosed.Diabetes.Percentage[county.diab$FIPS==cancer.data.female$FIPS[i]]
  } else {
    cancer.data.female$diab[i] <- NA
  }
  
  if(sum(county.inact$FIPS==cancer.data.female$FIPS[i])==1){
    cancer.data.female$inact[i] <- 
      county.inact$Physical.Inactivity.Percentage[county.inact$FIPS==cancer.data.female$FIPS[i]]
  } else {
    cancer.data.female$inact[i] <- NA
  }
  
  if(sum(county.obesity$FIPS==cancer.data.female$FIPS[i])==1){
    cancer.data.female$obesity[i] <- 
      county.obesity$Obesity.Percentage[county.obesity$FIPS==cancer.data.female$FIPS[i]]
  } else {
    cancer.data.female$obesity[i] <- NA
  }
}

cancer.data.female$AGE_ADJUSTED_RATE <- as.numeric(cancer.data.female$AGE_ADJUSTED_RATE)

glm.aar.elev <- glm(formula = AGE_ADJUSTED_RATE ~ elevation, 
                    family = poisson(link = "log"), 
                    data = cancer.data.female)
summary(glm.aar.elev)

ggplot(data = glm.aar.elev, aes(x = elevation, y = log(AGE_ADJUSTED_RATE)))+
  geom_point()+
  geom_abline(aes(intercept = glm.aar.elev$coefficients[1], 
                  slope = glm.aar.elev$coefficients[2]))+
  labs(x = "Elevation (m)", y = "ln(Age adjusted cancer mortality rate)",
       title = "Elevation by ln(AAMR) for females")+
  theme_minimal()

